##############################  Test endpoints ###################################
###
GET http://localhost:8081/ping

### Get swagger JSON
GET http://localhost:8080/swagger/

###Get veresion
GET http://localhost:8080/example-app/v1/version

###
GET http://localhost:8081/ready

###
GET http://localhost:8081/healthz

###
#Get books
POST http://localhost:8080/example-app/v1/books
Content-Type: application/json

{
  "name": "The Three Musketeers7",
  "price": 10.44,
  "genre": 1,
  "amount": 5
}


###
#Get book
GET http://localhost:8080/example-app/v1/books/2
Content-Type: application/json

###
#Get books
GET http://localhost:8080/example-app/v1/books
Content-Type: application/json


###Get books with filtering
GET http://localhost:8080/example-app/v1/books?_filter=name=="The Three Musketeers"
Content-Type: application/json

###Get books with filtering
GET http://localhost:8080/example-app/v1/books?_filter=genre==1
Content-Type: application/json

### Delete book
DELETE http://localhost:8080/example-app/v1/books/3
Content-Type: application/json
